# Generated by Django 5.2.1 on 2025-06-21 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workerdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='workerdetails',
            name='phone_no',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
