# Generated by Django 5.2.1 on 2025-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_remove_workerdetails_email_workerdetails_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
