# Generated by Django 5.2.1 on 2025-06-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('qualifications', models.CharField(max_length=100)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerdetails')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.job')),
            ],
        ),
    ]
