# Generated by Django 5.2.1 on 2025-06-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_job_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='', max_length=300),
        ),
    ]
